Wrpd enhancement 169
wrappid/service-core pull request #171
Opened 2024-06-02 08:10 UTC by balasai45

## Description

Created a generic Swagger Generate functionality which fetches data from database and populated the swagger json

## Related Issues

#169 It resolves this issue

## Checklist

- [ ] I have performed a thorough self-review of my code.
- [ ] My code follows the project's style guidelines and best practices.
- [ ] I have added or updated relevant comments in my code.
- [ ] I have resolved any merge conflicts of my branch.

## Screenshots (if applicable)
![image](https://github.com/wrappid/service-core/assets/67778565/de81d36d-31bf-4937-8efc-61173ee0cc55)
![image](https://github.com/wrappid/service-core/assets/67778565/956222f6-ab3c-44d4-8a8e-ce20910249da)

## Reviewers

@techoneel

2024-06-02 08:15 UTC, techoneel requested changes
Please work on the requested changes and commit again.

2024-06-02 08:15 UTC, techoneel commented on package/WrappidApp.ts
> +    package: {},
Additional comma

2024-06-02 08:15 UTC, techoneel commented on package/swagger/swagger-generate.ts
> +  const models = ApplicationContext.getContext(constant.registry.MODELS__REGISTRY);
Type declaration missing

2024-06-02 08:42 UTC, balasai45 commented
Committed fixes

2024-06-05 06:41 UTC, wrappidcare commented
Merging since stale over 24hrs.

2024-06-05 06:41 UTC, merged